// Generated by CoffeeScript 1.6.3
(function() {
  var direct;

  direct = function(opts) {
    if (!$.isPlainObject(opts)) {
      return;
    }
    return _.reduce(_.pairs(opts), function(memo, opt) {
      var fn;
      fn = director.directives[opt[0]] || $.fn[opt[0]];
      if (!_.isFunction(fn)) {
        return memo;
      }
      return fn.call(memo, opt[1]);
    }, $(this));
  };

  this.director = {
    direct: function(el) {
      if (el == null) {
        el = "html";
      }
      return $(el).find("[data-direct]").each(function() {
        return direct.call(this, $(this).data('direct'));
      });
    },
    directives: {}
  };

}).call(this);
